# This docker-compose file will creat 3 containers Elasticsearch, Kibana and Logstash

version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.16.3
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.16.3
    ports:
      - '5601:5601'

  logstash:
    image: logstash:7.16.3
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: /data/config-dir
        target: /usr/share/logstash/pipeline
        read_only: true
